export const Colors = {
  primary: "#000000ff",
  secondary: "#6C63FF",
  background: "#f5f5f5",
  surface: "#ffffff",
  border: "rgba(0,0,0,0.1)",

  text: {
    primary: "#000000",
    secondary: "#555555",
    muted: "#888888",
    light: "#ffffff",
  },

  light: {
    background: "#ffffff",
    oppositeBG: "#000000",
    surface: "#f5f5f5",
    oppositeSurface: "#252728",
    textPrimary: "#000000",
    textOppositePrimary: "#ffffff",
    textSecondary: "#555555",
    tabActive: "#000",
    tabInactive: "#fff",
    title: "#111111",
    layoutBackground: "#000000",
    shadow: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.1,
      shadowRadius: 6,
      elevation: 8,
    },
  },
  dark: {
    background: "#000000",
    oppositeBG: "#ffffff",
    surface: "#252728",
    oppositeSurface: "#f5f5f5",
    textPrimary: "#ffffff",
    textOppositePrimary: "#000000",
    textSecondary: "#cccccc",
    tabActive: "#fff",
    tabInactive: "#000",
    title: "#ffffff",
    layoutBackground: "#252728",
    shadow: {
      shadowColor: "#ffffffff",
      shadowOffset: { width: 0, height: -2 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 10,
    },
  },
};
